deploy-server:
  script:
    - ./gradlew server:distZip
    - cp server/build/distributions/serve*.zip /home/shark/Serveurs/Ylinor/Epsilon/Temp/server.zip
    - cd /home/shark/Serveurs/Ylinor/Epsilon/
    - screen -X -S epsilon quit || echo
    - unzip Temp/server.zip
    - screen -dmS epsilon "server/bin/server"