deploy-server:
  script:
    - gradle server:distZip
    - cp server/build/distributions/serve*.zip /home/shark/Serveurs/Ylinor/Epsilon/Temp/server.zip
    - cd /home/shark/Serveurs/Ylinor/Epsilon/
    - bash stop.bash
    - unzip Temp/server.zip
    - bash launch.bash
